spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/spring_security?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true
  redis:
    database: 0
    password: zjx!@#
    # 连接池最大连接数（使用负值表示没有限制）
    timeout: 1000 # 连接超时时间（毫秒）
    cluster:
      nodes: 192.168.232.88:6379,192.168.232.88:6380,192.168.232.88:6381
      max-redirects: 3
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接


server:
  port: 8888

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.jx.security.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true
 #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用



#图片验证码相关属性
#图片宽度
jx.security.validateCode.imageCode.imgWidth: 100
#图片高度
jx.security.validateCode.imageCode.imgHeight: 30
#验证码字符数
jx.security.validateCode.imageCode.codeNum: 4
#验证码图片干扰线数量
jx.security.validateCode.imageCode.lineCount: 50
#验证码过期时间
jx.security.validateCode.imageCode.expireTime: 60
#需要图形验证码的url
jx.security.validateCode.imageCode.urls: /auth/login
#前端传过来的uuid对应参数名
jx.security.validateCode.imageCode.uuidParamName: imageCodeUuid
#前端传过来的验证码对应参数名
jx.security.validateCode.imageCode.validateCodeParamName: imageValidateCode

#短信验证码相关属性
#验证码字符数
jx.security.validateCode.smsCode.codeNum: 4
#需要短信验证码的url
jx.security.validateCode.smsCode.urls:
#前端传过来的uuid对应参数名
jx.security.validateCode.smsCode.uuidParamName: smsCodeUuid
#前端传过来的验证码对应参数名
jx.security.validateCode.smsCode.validateCodeParamName: smsValidateCode
#前端传过来的电话号码对应参数名
jx.security.validateCode.smsCode.phoneNumberParamName: phoneNumber


